"""initial schema

Revision ID: 4a4952489ae7
Revises: 
Create Date: 2026-02-27 07:52:25.894627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4952489ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_status_category', ['status', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'players', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['updated_by'], ['id'])

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courts_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(None, 'players', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['created_by'], ['id'])

    with op.batch_alter_table('dropout_refunds', schema=None) as batch_op:
        batch_op.create_index('idx_refund_player_status', ['player_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropout_refunds_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropout_refunds_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dropout_refunds_status'), ['status'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_player_id'), ['player_id'], unique=False)
        batch_op.create_foreign_key(None, 'players', ['updated_by'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['created_by'], ['id'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_is_archived'), ['is_archived'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_is_archived'))
        batch_op.drop_index(batch_op.f('ix_sessions_date'))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_is_approved'))
        batch_op.drop_index(batch_op.f('ix_players_is_active'))
        batch_op.drop_index(batch_op.f('ix_players_email'))
        batch_op.drop_index(batch_op.f('ix_players_category'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_player_id'))
        batch_op.drop_index(batch_op.f('ix_payments_date'))

    with op.batch_alter_table('dropout_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dropout_refunds_status'))
        batch_op.drop_index(batch_op.f('ix_dropout_refunds_session_id'))
        batch_op.drop_index(batch_op.f('ix_dropout_refunds_player_id'))
        batch_op.drop_index('idx_refund_player_status')

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_courts_session_id'))

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attendances_status'))
        batch_op.drop_index(batch_op.f('ix_attendances_session_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_player_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_payment_status'))
        batch_op.drop_index(batch_op.f('ix_attendances_category'))
        batch_op.drop_index('idx_attendance_status_category')

    # ### end Alembic commands ###
